services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    user: ${HOST_USER:-}
    working_dir: /workspace
    environment:
      HISTFILE: /workspace/var/.docker_history
    volumes:
      - .:/workspace:cached
    networks:
      - podlodka.php_crew.nats
    tty: true
    init: true

  nats:
    image: nats:2.10
    command: -c /etc/nats/server.conf
    volumes:
      - ./docker/nats/server.conf:/etc/nats/server.conf
    ports:
      - "8222:8222"
    networks:
      - podlodka.php_crew.nats

networks:
  podlodka.php_crew.nats: ~
